/*using System;
using System.Text;
using System.Collections.Generic;
using Gstd.GstdUtility;*/
using Gstd.Script;
//using Gstd.Logger;

namespace Common.StgStageScript
{
    sealed class StgFunction
    {
        public static Function[] stgFunction = {/*
            //STG���ʊ֐��F���ʃf�[�^
            new Function("SaveCommonDataAreaToReplayFile", new Callback(Func_SaveCommonDataAreaToReplayFile), 1),
            new Function("LoadCommonDataAreaFromReplayFile", new Callback(Func_LoadCommonDataAreaFromReplayFile), 1),

            //STG���ʊ֐��F�V�X�e���֘A
            new Function("GetMainStgScriptPath", new Callback(Func_GetMainStgScriptPath), 0),
            new Function("GetMainStgScriptDirectory", new Callback(Func_GetMainStgScriptDirectory), 0),
            new Function("SetStgFrame", new Callback(Func_SetStgFrame), 6),
            new Function("SetItemRenderPriorityI", new Callback(Func_SetItemRenderPriorityI), 1),
            new Function("SetShotRenderPriorityI", new Callback(Func_SetShotRenderPriorityI), 1),
            new Function("GetStgFrameRenderPriorityMinI", new Callback(Func_GetStgFrameRenderPriorityMinI), 0),
            new Function("GetStgFrameRenderPriorityMaxI", new Callback(Func_GetStgFrameRenderPriorityMaxI), 0),
            new Function("GetItemRenderPriorityI", new Callback(Func_GetItemRenderPriorityI), 0),
            new Function("GetShotRenderPriorityI", new Callback(Func_GetShotRenderPriorityI), 0),
            new Function("GetPlayerRenderPriorityI", new Callback(Func_GetPlayerRenderPriorityI), 0),
            new Function("GetCameraFocusPermitPriorityI", new Callback(Func_GetCameraFocusPermitPriorityI), 0),
            new Function("CloseStgScene", new Callback(Func_CloseStgScene), 0),
            new Function("GetReplayFps", new Callback(Func_GetReplayFps), 0),

            //STG���ʊ֐��F���@
            new Function("GetPlayerObjectID", new Callback(Func_GetPlayerObjectID), 0),
            new Function("SetPlayerSpeed", new Callback(Func_SetPlayerSpeed), 2),
            new Function("SetPlayerClip", new Callback(Func_SetPlayerClip), 4),
            new Function("SetPlayerLife", new Callback(Func_SetPlayerLife), 1),
            new Function("SetPlayerSpell", new Callback(Func_SetPlayerSpell), 1),
            new Function("SetPlayerPower", new Callback(Func_SetPlayerPower), 1),
            new Function("SetPlayerInvincibilityFrame", new Callback(Func_SetPlayerInvincibilityFrame), 1),
            new Function("SetPlayerDownStateFrame", new Callback(Func_SetPlayerDownStateFrame), 1),
            new Function("SetPlayerRebirthFrame", new Callback(Func_SetPlayerRebirthFrame), 1),
            new Function("SetPlayerRebirthLossFrame", new Callback(Func_SetPlayerRebirthLossFrame), 1),
            new Function("SetPlayerAutoItemCollectLine", new Callback(Func_SetPlayerAutoItemCollectLine), 1),
            new Function("SetForbidPlayerShot", new Callback(Func_SetForbidPlayerShot), 1),
            new Function("SetForbidPlayerSpell", new Callback(Func_SetForbidPlayerSpell), 1),
            new Function("GetPlayerX", new Callback(Func_GetPlayerX), 0),
            new Function("GetPlayerY", new Callback(Func_GetPlayerY), 0),
            new Function("GetPlayerState", new Callback(Func_GetPlayerState), 0),
            new Function("GetPlayerSpeed", new Callback(Func_GetPlayerSpeed), 0),
            new Function("GetPlayerClip", new Callback(Func_GetPlayerClip), 0),
            new Function("GetPlayerLife", new Callback(Func_GetPlayerLife), 0),
            new Function("GetPlayerSpell", new Callback(Func_GetPlayerSpell), 0),
            new Function("GetPlayerPower", new Callback(Func_GetPlayerPower), 0),
            new Function("GetPlayerInvincibilityFrame", new Callback(Func_GetPlayerInvincibilityFrame), 0),
            new Function("GetPlayerDownStateFrame", new Callback(Func_GetPlayerDownStateFrame), 0),
            new Function("GetPlayerRebirthFrame", new Callback(Func_GetPlayerRebirthFrame), 0),
            new Function("GetAngleToPlayer", new Callback(Func_GetAngleToPlayer), 1),
            new Function("IsPermitPlayerShot", new Callback(Func_IsPermitPlayerShot), 0),
            new Function("IsPermitPlayerSpell", new Callback(Func_IsPermitPlayerSpell), 0),
            new Function("IsPlayerLastSpellWait", new Callback(Func_IsPlayerLastSpellWait), 0),
            new Function("IsPlayerSpellActive", new Callback(Func_IsPlayerSpellActive), 0),
            new Function("GetPlayerScriptID", new Callback(Func_GetPlayerScriptID), 0),

            //STG���ʊ֐��F�G
            new Function("GetEnemyBossSceneObjectID", new Callback(Func_GetEnemyBossSceneObjectID), 0),
            new Function("GetEnemyBossObjectID", new Callback(Func_GetEnemyBossObjectID), 0),
            new Function("GetAllEnemyID", new Callback(Func_GetAllEnemyID), 0),
            new Function("GetIntersectionRegistedEnemyID", new Callback(Func_GetIntersectionRegistedEnemyID), 0),
            new Function("GetAllEnemyIntersectionPosition", new Callback(Func_GetAllEnemyIntersectionPosition), 0),
            new Function("GetEnemyIntersectionPosition", new Callback(Func_GetEnemyIntersectionPosition), 3),
            new Function("GetEnemyIntersectionPositionByIdA1", new Callback(Func_GetEnemyIntersectionPositionByIdA1), 1),
            new Function("GetEnemyIntersectionPositionByIdA2", new Callback(Func_GetEnemyIntersectionPositionByIdA2), 3),
            new Function("LoadEnemyShotData", new Callback(Func_LoadEnemyShotData), 1),
            new Function("ReloadEnemyShotData", new Callback(Func_ReloadEnemyShotData), 1),

            //STG���ʊ֐��F�e
            new Function("DeleteShotAll", new Callback(Func_DeleteShotAll), 2),
            new Function("DeleteShotInCircle", new Callback(Func_DeleteShotInCircle), 5),
            new Function("CreateShotA1", new Callback(Func_CreateShotA1), 6),
            new Function("CreateShotA2", new Callback(Func_CreateShotA2), 8),
            new Function("CreateShotOA1", new Callback(Func_CreateShotOA1), 5),
            new Function("CreateShotB1", new Callback(Func_CreateShotB1), 6),
            new Function("CreateShotB2", new Callback(Func_CreateShotB2), 10),
            new Function("CreateShotOB1", new Callback(Func_CreateShotOB1), 5),
            new Function("CreateLooseLaserA1", new Callback(Func_CreateLooseLaserA1), 8),
            new Function("CreateStraightLaserA1", new Callback(Func_CreateStraightLaserA1), 8),
            new Function("CreateCurveLaserA1", new Callback(Func_CreateCurveLaserA1), 8),
            //new Function("StgStraightLaserA1", new Callback(Func_CreateStraightLaserA1), 8),
            new Function("SetShotIntersectionCircle", new Callback(Func_SetShotIntersectionCircle), 3),
            new Function("SetShotIntersectionLine", new Callback(Func_SetShotIntersectionLine), 5),
            new Function("GetShotIdInCircleA1", new Callback(Func_GetShotIdInCircleA1), 3),
            new Function("GetShotIdInCircleA2", new Callback(Func_GetShotIdInCircleA2), 4),
            new Function("GetShotCount", new Callback(Func_GetShotCount), 1),
            new Function("SetShotAutoDeleteClip", new Callback(Func_SetShotAutoDeleteClip), 4),
            new Function("GetShotDataInfoA1", new Callback(Func_GetShotDataInfoA1), 3),
            new Function("StartShotScript", new Callback(Func_StartShotScript), 1),

            //STG���ʊ֐��F�A�C�e��
            new Function("CreateItemA1", new Callback(Func_CreateItemA1), 4),
            new Function("CreateItemA2", new Callback(Func_CreateItemA2), 6),
            new Function("CreateItemU1", new Callback(Func_CreateItemU1), 4),
            new Function("CreateItemU2", new Callback(Func_CreateItemU2), 6),
            new Function("CreateItemScore", new Callback(Func_CreateItemScore), 3),
            new Function("CollectAllItems", new Callback(Func_CollectAllItems), 0),
            new Function("CollectItemsByType", new Callback(Func_CollectItemsByType), 1),
            new Function("CollectItemsInCircle", new Callback(Func_CollectItemsInCircle), 3),
            new Function("CancelCollectItems", new Callback(Func_CancelCollectItems), 0),
            new Function("StartItemScript", new Callback(Func_StartItemScript), 1),
            new Function("SetDefaultBonusItemEnable", new Callback(Func_SetDefaultBonusItemEnable), 1),
            new Function("LoadItemData", new Callback(Func_LoadItemData), 1),
            new Function("ReloadItemData", new Callback(Func_ReloadItemData), 1),

            //STG���ʊ֐��F���̑�
            new Function("StartSlow", new Callback(Func_StartSlow), 2),
            new Function("StopSlow", new Callback(Func_StopSlow), 1),
            new Function("IsIntersected_Line_Circle", new Callback(Func_IsIntersected_Line_Circle), 8),
            new Function("IsIntersected_Obj_Obj", new Callback(Func_IsIntersected_Obj_Obj), 2),

            //STG���ʊ֐��F�ړ��I�u�W�F�N�g����
            new Function("ObjMove_SetX", new Callback(Func_ObjMove_SetX), 2),
            new Function("ObjMove_SetY", new Callback(Func_ObjMove_SetY), 2),
            new Function("ObjMove_SetPosition", new Callback(Func_ObjMove_SetPosition), 3),
            new Function("ObjMove_SetSpeed", new Callback(Func_ObjMove_SetSpeed), 2),
            new Function("ObjMove_SetAngle", new Callback(Func_ObjMove_SetAngle), 2),
            new Function("ObjMove_SetAcceleration", new Callback(Func_ObjMove_SetAcceleration), 2),
            new Function("ObjMove_SetMaxSpeed", new Callback(Func_ObjMove_SetMaxSpeed), 2),
            new Function("ObjMove_SetAngularVelocity", new Callback(Func_ObjMove_SetAngularVelocity), 2),
            new Function("ObjMove_SetDestAtSpeed", new Callback(Func_ObjMove_SetDestAtSpeed), 4),
            new Function("ObjMove_SetDestAtFrame", new Callback(Func_ObjMove_SetDestAtFrame), 4),
            new Function("ObjMove_SetDestAtWeight", new Callback(Func_ObjMove_SetDestAtWeight), 5),
            new Function("ObjMove_AddPatternA1", new Callback(Func_ObjMove_AddPatternA1), 4),
            new Function("ObjMove_AddPatternA2", new Callback(Func_ObjMove_AddPatternA2), 7),
            new Function("ObjMove_AddPatternA3", new Callback(Func_ObjMove_AddPatternA3), 8),
            new Function("ObjMove_AddPatternA4", new Callback(Func_ObjMove_AddPatternA4), 9),
            new Function("ObjMove_AddPatternB1", new Callback(Func_ObjMove_AddPatternB1), 4),
            new Function("ObjMove_AddPatternB2", new Callback(Func_ObjMove_AddPatternB2), 8),
            new Function("ObjMove_AddPatternB3", new Callback(Func_ObjMove_AddPatternB3), 9),
            new Function("ObjMove_GetX", new Callback(Func_ObjMove_GetX), 1),
            new Function("ObjMove_GetY", new Callback(Func_ObjMove_GetY), 1),
            new Function("ObjMove_GetSpeed", new Callback(Func_ObjMove_GetSpeed), 1),
            new Function("ObjMove_GetAngle", new Callback(Func_ObjMove_GetAngle), 1),

            //STG���ʊ֐��F�G�I�u�W�F�N�g����
            new Function("ObjEnemy_Create", new Callback(Func_ObjEnemy_Create), 1),
            new Function("ObjEnemy_Regist", new Callback(Func_ObjEnemy_Regist), 1),
            new Function("ObjEnemy_GetInfo", new Callback(Func_ObjEnemy_GetInfo), 2),
            new Function("ObjEnemy_SetLife", new Callback(Func_ObjEnemy_SetLife), 2),
            new Function("ObjEnemy_AddLife", new Callback(Func_ObjEnemy_AddLife), 2),
            new Function("ObjEnemy_SetDamageRate", new Callback(Func_ObjEnemy_SetDamageRate), 3),
            new Function("ObjEnemy_AddIntersectionCircleA", new Callback(Func_ObjEnemy_AddIntersectionCircleA), 4),
            new Function("ObjEnemy_SetIntersectionCircleToShot", new Callback(Func_ObjEnemy_SetIntersectionCircleToShot), 4),
            new Function("ObjEnemy_SetIntersectionCircleToPlayer", new Callback(Func_ObjEnemy_SetIntersectionCircleToPlayer), 4),

            //STG���ʊ֐��F�G�{�X�V�[���I�u�W�F�N�g����
            new Function("ObjEnemyBossScene_Create", new Callback(Func_ObjEnemyBossScene_Create), 0),
            new Function("ObjEnemyBossScene_Regist", new Callback(Func_ObjEnemyBossScene_Regist), 1),
            new Function("ObjEnemyBossScene_Add", new Callback(Func_ObjEnemyBossScene_Add), 3),
            new Function("ObjEnemyBossScene_LoadInThread", new Callback(Func_ObjEnemyBossScene_LoadInThread), 1),
            new Function("ObjEnemyBossScene_GetInfo", new Callback(Func_ObjEnemyBossScene_GetInfo), 2),
            new Function("ObjEnemyBossScene_SetSpellTimer", new Callback(Func_ObjEnemyBossScene_SetSpellTimer), 2),
            new Function("ObjEnemyBossScene_StartSpell", new Callback(Func_ObjEnemyBossScene_StartSpell), 1),

            //STG���ʊ֐��F�e�I�u�W�F�N�g����
            new Function("ObjShot_Create", new Callback(Func_ObjShot_Create), 1),
            new Function("ObjShot_Regist", new Callback(Func_ObjShot_Regist), 1),
            new Function("ObjShot_SetAutoDelete", new Callback(Func_ObjShot_SetAutoDelete), 2),
            new Function("ObjShot_FadeDelete", new Callback(Func_ObjShot_FadeDelete), 1),
            new Function("ObjShot_SetDeleteFrame", new Callback(Func_ObjShot_SetDeleteFrame), 2),
            new Function("ObjShot_SetDelay", new Callback(Func_ObjShot_SetDelay), 2),
            new Function("ObjShot_SetSpellResist", new Callback(Func_ObjShot_SetSpellResist), 2),
            new Function("ObjShot_SetGraphic", new Callback(Func_ObjShot_SetGraphic), 2),
            new Function("ObjShot_SetSourceBlendType", new Callback(Func_ObjShot_SetSourceBlendType), 2),
            new Function("ObjShot_SetDamage", new Callback(Func_ObjShot_SetDamage), 2),
            new Function("ObjShot_SetPenetration", new Callback(Func_ObjShot_SetPenetration), 2),
            new Function("ObjShot_SetEraseShot", new Callback(Func_ObjShot_SetEraseShot), 2),
            new Function("ObjShot_SetSpellFactor", new Callback(Func_ObjShot_SetSpellFactor), 2),
            new Function("ObjShot_ToItem", new Callback(Func_ObjShot_ToItem), 1),
            new Function("ObjShot_AddShotA1", new Callback(Func_ObjShot_AddShotA1), 3),
            new Function("ObjShot_AddShotA2", new Callback(Func_ObjShot_AddShotA2), 5),
            new Function("ObjShot_SetIntersectionCircleA1", new Callback(Func_ObjShot_SetIntersectionCircleA1), 2),
            new Function("ObjShot_SetIntersectionCircleA2", new Callback(Func_ObjShot_SetIntersectionCircleA2), 4),
            new Function("ObjShot_SetIntersectionLine", new Callback(Func_ObjShot_SetIntersectionLine), 6),
            new Function("ObjShot_SetIntersectionEnable", new Callback(Func_ObjShot_SetIntersectionEnable), 2),
            new Function("ObjShot_SetItemChange", new Callback(Func_ObjShot_SetItemChange), 2),
            new Function("ObjShot_GetDelay", new Callback(Func_ObjShot_GetDelay), 1),
            new Function("ObjShot_GetDamage", new Callback(Func_ObjShot_GetDamage), 1),
            new Function("ObjShot_GetPenetration", new Callback(Func_ObjShot_GetPenetration), 1),
            new Function("ObjShot_IsSpellResist", new Callback(Func_ObjShot_IsSpellResist), 1),
            new Function("ObjShot_GetImageID", new Callback(Func_ObjShot_GetImageID), 1),

            new Function("ObjLaser_SetLength", new Callback(Func_ObjLaser_SetLength), 2),
            new Function("ObjLaser_SetRenderWidth", new Callback(Func_ObjLaser_SetRenderWidth), 2),
            new Function("ObjLaser_SetIntersectionWidth", new Callback(Func_ObjLaser_SetIntersectionWidth), 2),
            new Function("ObjLaser_SetInvalidLength", new Callback(Func_ObjLaser_SetInvalidLength), 3),
            new Function("ObjLaser_SetGrazeInvalidFrame", new Callback(Func_ObjLaser_SetGrazeInvalidFrame), 2),
            new Function("ObjLaser_SetItemDistance", new Callback(Func_ObjLaser_SetItemDistance), 2),
            new Function("ObjLaser_GetLength", new Callback(Func_ObjLaser_GetLength), 1),
            new Function("ObjLaser_GetRenderWidth", new Callback(Func_ObjLaser_GetRenderWidth), 1),
            new Function("ObjLaser_GetIntersectionWidth", new Callback(Func_ObjLaser_GetIntersectionWidth), 1),
            new Function("ObjStLaser_SetAngle", new Callback(Func_ObjStLaser_SetAngle), 2),
            new Function("ObjStLaser_GetAngle", new Callback(Func_ObjStLaser_GetAngle), 1),
            new Function("ObjStLaser_SetSource", new Callback(Func_ObjStLaser_SetSource), 2),
            new Function("ObjCrLaser_SetTipDecrement", new Callback(Func_ObjCrLaser_SetTipDecrement), 2),

            //STG���ʊ֐��F�A�C�e���I�u�W�F�N�g����
            new Function("ObjItem_Create", new Callback(Func_ObjItem_Create), 1),
            new Function("ObjItem_Regist", new Callback(Func_ObjItem_Regist), 1),
            new Function("ObjItem_SetItemID", new Callback(Func_ObjItem_SetItemID), 2),
            new Function("ObjItem_SetRenderScoreEnable", new Callback(Func_ObjItem_SetRenderScoreEnable), 2),
            new Function("ObjItem_SetAutoCollectEnable", new Callback(Func_ObjItem_SetAutoCollectEnable), 2),
            new Function("ObjItem_SetDefinedMovePatternA1", new Callback(Func_ObjItem_SetDefinedMovePatternA1), 2),
            new Function("ObjItem_GetInfo", new Callback(Func_ObjItem_GetInfo), 2),

            //STG���ʊ֐��F���@�I�u�W�F�N�g����
            new Function("ObjPlayer_AddIntersectionCircleA1", new Callback(Func_ObjPlayer_AddIntersectionCircleA1), 5),
            new Function("ObjPlayer_AddIntersectionCircleA2", new Callback(Func_ObjPlayer_AddIntersectionCircleA2), 4),
            new Function("ObjPlayer_ClearIntersection", new Callback(Func_ObjPlayer_ClearIntersection), 1),

            //STG���ʊ֐��F�����蔻��I�u�W�F�N�g����
            new Function("ObjCol_IsIntersected", new Callback(Func_ObjCol_IsIntersected), 1),
            new Function("ObjCol_GetListOfIntersectedEnemyID", new Callback(Func_ObjCol_GetListOfIntersectedEnemyID), 1),
            new Function("ObjCol_GetIntersectedCount", new Callback(Func_ObjCol_GetIntersectedCount), 1),

            //�萔
            new Function("SCREEN_WIDTH"), constant<640>::func), 0),
            new Function("SCREEN_HEIGHT"), constant<480>::func), 0),
            new Function("TYPE_ALL"), constant<StgStageScript::TYPE_ALL>::func), 0),
            new Function("TYPE_SHOT"), constant<StgStageScript::TYPE_SHOT>::func), 0),
            new Function("TYPE_CHILD"), constant<StgStageScript::TYPE_CHILD>::func), 0),
            new Function("TYPE_IMMEDIATE"), constant<StgStageScript::TYPE_IMMEDIATE>::func), 0),
            new Function("TYPE_FADE"), constant<StgStageScript::TYPE_FADE>::func), 0),
            new Function("TYPE_ITEM"), constant<StgStageScript::TYPE_ITEM>::func), 0),

            new Function("STATE_NORMAL"), constant<StgPlayerObject::STATE_NORMAL>::func), 0),
            new Function("STATE_HIT"), constant<StgPlayerObject::STATE_HIT>::func), 0),
            new Function("STATE_DOWN"), constant<StgPlayerObject::STATE_DOWN>::func), 0),
            new Function("STATE_END"), constant<StgPlayerObject::STATE_END>::func), 0),

            new Function("ITEM_1UP"), constant<StgItemObject::ITEM_1UP>::func), 0),
            new Function("ITEM_1UP_S"), constant<StgItemObject::ITEM_1UP_S>::func), 0),
            new Function("ITEM_SPELL"), constant<StgItemObject::ITEM_SPELL>::func), 0),
            new Function("ITEM_SPELL_S"), constant<StgItemObject::ITEM_SPELL_S>::func), 0),
            new Function("ITEM_POWER"), constant<StgItemObject::ITEM_POWER>::func), 0),
            new Function("ITEM_POWER_S"), constant<StgItemObject::ITEM_POWER_S>::func), 0),
            new Function("ITEM_POINT"), constant<StgItemObject::ITEM_POINT>::func), 0),
            new Function("ITEM_POINT_S"), constant<StgItemObject::ITEM_POINT_S>::func), 0),
            new Function("ITEM_USER"), constant<StgItemObject::ITEM_USER>::func), 0),

            new Function("ITEM_MOVE_DOWN"), constant<StgMovePattern_Item::MOVE_DOWN>::func), 0),
            new Function("ITEM_MOVE_TOPLAYER"), constant<StgMovePattern_Item::MOVE_TOPLAYER>::func), 0),

            new Function("OBJ_PLAYER"), constant<StgStageScript::OBJ_PLAYER>::func), 0),
            new Function("OBJ_SPELL_MANAGE"), constant<StgStageScript::OBJ_SPELL_MANAGE>::func), 0),
            new Function("OBJ_SPELL"), constant<StgStageScript::OBJ_SPELL>::func), 0),
            new Function("OBJ_ENEMY"), constant<StgStageScript::OBJ_ENEMY>::func), 0),
            new Function("OBJ_ENEMY_BOSS"), constant<StgStageScript::OBJ_ENEMY_BOSS>::func), 0),
            new Function("OBJ_ENEMY_BOSS_SCENE"), constant<StgStageScript::OBJ_ENEMY_BOSS_SCENE>::func), 0),
            new Function("OBJ_SHOT"), constant<StgStageScript::OBJ_SHOT>::func), 0),
            new Function("OBJ_LOOSE_LASER"), constant<StgStageScript::OBJ_LOOSE_LASER>::func), 0),
            new Function("OBJ_STRAIGHT_LASER"), constant<StgStageScript::OBJ_STRAIGHT_LASER>::func), 0),
            new Function("OBJ_CURVE_LASER"), constant<StgStageScript::OBJ_CURVE_LASER>::func), 0),
            new Function("OBJ_ITEM"), constant<StgStageScript::OBJ_ITEM>::func), 0),

            new Function("INFO_LIFE"), constant<StgStageScript::INFO_LIFE>::func), 0),
            new Function("INFO_DAMAGE_RATE_SHOT"), constant<StgStageScript::INFO_DAMAGE_RATE_SHOT>::func), 0),
            new Function("INFO_DAMAGE_RATE_SPELL"), constant<StgStageScript::INFO_DAMAGE_RATE_SPELL>::func), 0),
            new Function("INFO_SHOT_HIT_COUNT"), constant<StgStageScript::INFO_SHOT_HIT_COUNT>::func), 0),
            new Function("INFO_TIMER"), constant<StgStageScript::INFO_TIMER>::func), 0),
            new Function("INFO_TIMERF"), constant<StgStageScript::INFO_TIMERF>::func), 0),
            new Function("INFO_ORGTIMERF"), constant<StgStageScript::INFO_ORGTIMERF>::func), 0),
            new Function("INFO_IS_SPELL"), constant<StgStageScript::INFO_IS_SPELL>::func), 0),
            new Function("INFO_IS_LAST_SPELL"), constant<StgStageScript::INFO_IS_LAST_SPELL>::func), 0),
            new Function("INFO_IS_DURABLE_SPELL"), constant<StgStageScript::INFO_IS_DURABLE_SPELL>::func), 0),
            new Function("INFO_SPELL_SCORE"), constant<StgStageScript::INFO_SPELL_SCORE>::func), 0),
            new Function("INFO_REMAIN_STEP_COUNT"), constant<StgStageScript::INFO_REMAIN_STEP_COUNT>::func), 0),
            new Function("INFO_ACTIVE_STEP_LIFE_COUNT"), constant<StgStageScript::INFO_ACTIVE_STEP_LIFE_COUNT>::func), 0),
            new Function("INFO_ACTIVE_STEP_TOTAL_MAX_LIFE"), constant<StgStageScript::INFO_ACTIVE_STEP_TOTAL_MAX_LIFE>::func), 0),
            new Function("INFO_ACTIVE_STEP_TOTAL_LIFE"), constant<StgStageScript::INFO_ACTIVE_STEP_TOTAL_LIFE>::func), 0),
            new Function("INFO_ACTIVE_STEP_LIFE_RATE_LIST"), constant<StgStageScript::INFO_ACTIVE_STEP_LIFE_RATE_LIST>::func), 0),
            new Function("INFO_IS_LAST_STEP"), constant<StgStageScript::INFO_IS_LAST_STEP>::func), 0),
            new Function("INFO_PLAYER_SHOOTDOWN_COUNT"), constant<StgStageScript::INFO_PLAYER_SHOOTDOWN_COUNT>::func), 0),
            new Function("INFO_PLAYER_SPELL_COUNT"), constant<StgStageScript::INFO_PLAYER_SPELL_COUNT>::func), 0),
            new Function("INFO_CURRENT_LIFE"), constant<StgStageScript::INFO_CURRENT_LIFE>::func), 0),
            new Function("INFO_CURRENT_LIFE_MAX"), constant<StgStageScript::INFO_CURRENT_LIFE_MAX>::func), 0),

            new Function("INFO_ITEM_SCORE"), constant<StgStageScript::INFO_ITEM_SCORE>::func), 0),

            new Function("INFO_RECT"), constant<StgStageScript::INFO_RECT>::func), 0),
            new Function("INFO_DELAY_COLOR"), constant<StgStageScript::INFO_DELAY_COLOR>::func), 0),
            new Function("INFO_BLEND"), constant<StgStageScript::INFO_BLEND>::func), 0),
            new Function("INFO_COLLISION"), constant<StgStageScript::INFO_COLLISION>::func), 0),
            new Function("INFO_COLLISION_LIST"), constant<StgStageScript::INFO_COLLISION_LIST>::func), 0),

            new Function("EV_REQUEST_LIFE"), constant<StgStageScript::EV_REQUEST_LIFE>::func), 0),
            new Function("EV_REQUEST_TIMER"), constant<StgStageScript::EV_REQUEST_TIMER>::func), 0),
            new Function("EV_REQUEST_IS_SPELL"), constant<StgStageScript::EV_REQUEST_IS_SPELL>::func), 0),
            new Function("EV_REQUEST_IS_LAST_SPELL"), constant<StgStageScript::EV_REQUEST_IS_LAST_SPELL>::func), 0),
            new Function("EV_REQUEST_IS_DURABLE_SPELL"), constant<StgStageScript::EV_REQUEST_IS_DURABLE_SPELL>::func), 0),
            new Function("EV_REQUEST_SPELL_SCORE"), constant<StgStageScript::EV_REQUEST_SPELL_SCORE>::func), 0),
            new Function("EV_REQUEST_REPLAY_TARGET_COMMON_AREA"), constant<StgStageScript::EV_REQUEST_REPLAY_TARGET_COMMON_AREA>::func), 0),

            new Function("EV_TIMEOUT"), constant<StgStageScript::EV_TIMEOUT>::func), 0),
            new Function("EV_START_BOSS_SPELL"), constant<StgStageScript::EV_START_BOSS_SPELL>::func), 0),
            new Function("EV_GAIN_SPELL"), constant<StgStageScript::EV_GAIN_SPELL>::func), 0),
            new Function("EV_START_BOSS_STEP"), constant<StgStageScript::EV_START_BOSS_STEP>::func), 0),
            new Function("EV_END_BOSS_STEP"), constant<StgStageScript::EV_END_BOSS_STEP>::func), 0),

            new Function("EV_PLAYER_SHOOTDOWN"), constant<StgStageScript::EV_PLAYER_SHOOTDOWN>::func), 0),
            new Function("EV_PLAYER_SPELL"), constant<StgStageScript::EV_PLAYER_SPELL>::func), 0),
            new Function("EV_PLAYER_REBIRTH"), constant<StgStageScript::EV_PLAYER_REBIRTH>::func), 0),

            new Function("EV_PAUSE_ENTER"), constant<StgStageScript::EV_PAUSE_ENTER>::func), 0),
            new Function("EV_PAUSE_LEAVE"), constant<StgStageScript::EV_PAUSE_LEAVE>::func), 0),

            new Function("TARGET_ALL"), constant<StgStageScript::TARGET_ALL>::func), 0),
            new Function("TARGET_ENEMY"), constant<StgStageScript::TARGET_ENEMY>::func), 0),
            new Function("TARGET_PLAYER"), constant<StgStageScript::TARGET_PLAYER>::func), 0),

            new Function("NO_CHANGE"), constant<StgMovePattern::NO_CHANGE>::func), 0),
        */};
    }
}
