/*using System;
using System.Text;
using System.Collections.Generic;
using Gstd.GstdUtility;*/
using Gstd.Script;

namespace Directx.DxScript
{
    sealed class DxFunction
    {
        public static Function[] dxFunction = {/*
            //Dx�֐��F�V�X�e���n�n
            new Function("InstallFont", new Callback(Func_InstallFont), 1),

            //Dx�֐��F�����n
            new Function("LoadSound", new Callback(Func_LoadSound), 1),
            new Function("RemoveSound", new Callback(Func_RemoveSound), 1),
            new Function("PlayBGM", new Callback(Func_PlayBGM), 3),
            new Function("PlaySE", new Callback(Func_PlaySE), 1),
            new Function("StopSound", new Callback(Func_StopSound), 1),

            //Dx�֐��F�L�[�n
            new Function("GetKeyState", new Callback(Func_GetKeyState), 1),
            new Function("GetMouseX", new Callback(Func_GetMouseX), 0),
            new Function("GetMouseY", new Callback(Func_GetMouseY), 0),
            new Function("GetMouseMoveZ", new Callback(Func_GetMouseMoveZ), 0),
            new Function("GetMouseState", new Callback(Func_GetMouseState), 1),
            new Function("GetVirtualKeyState", new Callback(Func_GetVirtualKeyState), 1),
            new Function("SetVirtualKeyState", new Callback(Func_SetVirtualKeyState), 2),

            //Dx�֐��F�`��n
            new Function("GetScreenWidth", new Callback(Func_GetScreenWidth), 0),
            new Function("GetScreenHeight", new Callback(Func_GetScreenHeight), 0),
            new Function("LoadTexture", new Callback(Func_LoadTexture), 1),
            new Function("LoadTextureInLoadThread", new Callback(Func_LoadTextureInLoadThread), 1),
            new Function("RemoveTexture", new Callback(Func_RemoveTexture), 1),
            new Function("GetTextureWidth", new Callback(Func_GetTextureWidth), 1),
            new Function("GetTextureHeight", new Callback(Func_GetTextureHeight), 1),
            new Function("SetFogEnable", new Callback(Func_SetFogEnable), 1),
            new Function("SetFogParam", new Callback(Func_SetFogParam), 5),
            new Function("CreateRenderTarget", new Callback(Func_CreateRenderTarget), 1),
            new Function("SetRenderTarget", new Callback(Func_SetRenderTarget), 1),
            new Function("GetTransitionRenderTargetName", new Callback(Func_GetTransitionRenderTargetName), 0),
            new Function("SaveRenderedTextureA1", new Callback(Func_SaveRenderedTextureA1), 2),
            new Function("SaveRenderedTextureA2", new Callback(Func_SaveRenderedTextureA2), 6),
            new Function("IsPixelShaderSupported", new Callback(Func_IsPixelShaderSupported), 2),
            new Function("SetShader", new Callback(Func_SetShader), 3),
            new Function("SetShaderI", new Callback(Func_SetShaderI), 3),
            new Function("ResetShader", new Callback(Func_ResetShader), 2),
            new Function("ResetShaderI", new Callback(Func_ResetShaderI), 2),

            //Dx�֐��F�J����3D
            new Function("SetCameraFocusX", new Callback(Func_SetCameraFocusX), 1),
            new Function("SetCameraFocusY", new Callback(Func_SetCameraFocusY), 1),
            new Function("SetCameraFocusZ", new Callback(Func_SetCameraFocusZ), 1),
            new Function("SetCameraFocusXYZ", new Callback(Func_SetCameraFocusXYZ), 3),
            new Function("SetCameraRadius", new Callback(Func_SetCameraRadius), 1),
            new Function("SetCameraAzimuthAngle", new Callback(Func_SetCameraAzimuthAngle), 1),
            new Function("SetCameraElevationAngle", new Callback(Func_SetCameraElevationAngle), 1),
            new Function("SetCameraYaw", new Callback(Func_SetCameraYaw), 1),
            new Function("SetCameraPitch", new Callback(Func_SetCameraPitch), 1),
            new Function("SetCameraRoll", new Callback(Func_SetCameraRoll), 1),
            new Function("GetCameraX", new Callback(Func_GetCameraX), 0),
            new Function("GetCameraY", new Callback(Func_GetCameraY), 0),
            new Function("GetCameraZ", new Callback(Func_GetCameraZ), 0),
            new Function("GetCameraFocusX", new Callback(Func_GetCameraFocusX), 0),
            new Function("GetCameraFocusY", new Callback(Func_GetCameraFocusY), 0),
            new Function("GetCameraFocusZ", new Callback(Func_GetCameraFocusZ), 0),
            new Function("GetCameraRadius", new Callback(Func_GetCameraRadius), 0),
            new Function("GetCameraAzimuthAngle", new Callback(Func_GetCameraAzimuthAngle), 0),
            new Function("GetCameraElevationAngle", new Callback(Func_GetCameraElevationAngle), 0),
            new Function("GetCameraYaw", new Callback(Func_GetCameraYaw), 0),
            new Function("GetCameraPitch", new Callback(Func_GetCameraPitch), 0),
            new Function("GetCameraRoll", new Callback(Func_GetCameraRoll), 0),
            new Function("SetCameraPerspectiveClip", new Callback(Func_SetCameraPerspectiveClip), 2),

            //Dx�֐��F�J����2D
            new Function("Set2DCameraFocusX", new Callback(Func_Set2DCameraFocusX), 1),
            new Function("Set2DCameraFocusY", new Callback(Func_Set2DCameraFocusY), 1),
            new Function("Set2DCameraAngleZ", new Callback(Func_Set2DCameraAngleZ), 1),
            new Function("Set2DCameraRatio", new Callback(Func_Set2DCameraRatio), 1),
            new Function("Set2DCameraRatioX", new Callback(Func_Set2DCameraRatioX), 1),
            new Function("Set2DCameraRatioY", new Callback(Func_Set2DCameraRatioY), 1),
            new Function("Reset2DCamera", new Callback(Func_Reset2DCamera), 0),
            new Function("Get2DCameraX", new Callback(Func_Get2DCameraX), 0),
            new Function("Get2DCameraY", new Callback(Func_Get2DCameraY), 0),
            new Function("Get2DCameraAngleZ", new Callback(Func_Get2DCameraAngleZ), 0),
            new Function("Get2DCameraRatio", new Callback(Func_Get2DCameraRatio), 0),
            new Function("Get2DCameraRatioX", new Callback(Func_Get2DCameraRatioX), 0),
            new Function("Get2DCameraRatioY", new Callback(Func_Get2DCameraRatioY), 0),

            //Dx�֐��F���̑�
            new Function("GetObjectDistance", new Callback(Func_GetObjectDistance), 2),
            new Function("GetObject2dPosition", new Callback(Func_GetObject2dPosition), 1),
            new Function("Get2dPosition", new Callback(Func_Get2dPosition), 3),

            //Dx�֐��F�I�u�W�F�N�g����(����)
            new Function("Obj_Delete", new Callback(Func_Obj_Delete), 1),
            new Function("Obj_IsDeleted", new Callback(Func_Obj_IsDeleted), 1),
            new Function("Obj_SetVisible", new Callback(Func_Obj_SetVisible), 2),
            new Function("Obj_IsVisible", new Callback(Func_Obj_IsVisible), 1),
            new Function("Obj_SetRenderPriority", new Callback(Func_Obj_SetRenderPriority), 2),
            new Function("Obj_SetRenderPriorityI", new Callback(Func_Obj_SetRenderPriorityI), 2),
            new Function("Obj_GetRenderPriority", new Callback(Func_Obj_GetRenderPriority), 1),
            new Function("Obj_GetRenderPriorityI", new Callback(Func_Obj_GetRenderPriorityI), 1),
            new Function("Obj_GetValue", new Callback(Func_Obj_GetValue), 2),
            new Function("Obj_GetValueD", new Callback(Func_Obj_GetValueD), 3),
            new Function("Obj_SetValue", new Callback(Func_Obj_SetValue), 3),
            new Function("Obj_DeleteValue", new Callback(Func_Obj_DeleteValue), 2),
            new Function("Obj_IsValueExists", new Callback(Func_Obj_IsValueExists), 2),
            new Function("Obj_GetType", new Callback(Func_Obj_GetType), 1),

            //Dx�֐��F�I�u�W�F�N�g����(RenderObject)
            new Function("ObjRender_SetX", new Callback(Func_ObjRender_SetX), 2),
            new Function("ObjRender_SetY", new Callback(Func_ObjRender_SetY), 2),
            new Function("ObjRender_SetZ", new Callback(Func_ObjRender_SetZ), 2),
            new Function("ObjRender_SetPosition", new Callback(Func_ObjRender_SetPosition), 4),
            new Function("ObjRender_SetAngleX", new Callback(Func_ObjRender_SetAngleX), 2),
            new Function("ObjRender_SetAngleY", new Callback(Func_ObjRender_SetAngleY), 2),
            new Function("ObjRender_SetAngleZ", new Callback(Func_ObjRender_SetAngleZ), 2),
            new Function("ObjRender_SetAngleXYZ", new Callback(Func_ObjRender_SetAngleXYZ), 4),
            new Function("ObjRender_SetScaleX", new Callback(Func_ObjRender_SetScaleX), 2),
            new Function("ObjRender_SetScaleY", new Callback(Func_ObjRender_SetScaleY), 2),
            new Function("ObjRender_SetScaleZ", new Callback(Func_ObjRender_SetScaleZ), 2),
            new Function("ObjRender_SetScaleXYZ", new Callback(Func_ObjRender_SetScaleXYZ), 4),
            new Function("ObjRender_SetColor", new Callback(Func_ObjRender_SetColor), 4),
            new Function("ObjRender_SetColorHSV", new Callback(Func_ObjRender_SetColorHSV), 4),
            new Function("ObjRender_SetAlpha", new Callback(Func_ObjRender_SetAlpha), 2),
            new Function("ObjRender_SetBlendType", new Callback(Func_ObjRender_SetBlendType), 2),
            new Function("ObjRender_GetX", new Callback(Func_ObjRender_GetX), 1),
            new Function("ObjRender_GetY", new Callback(Func_ObjRender_GetY), 1),
            new Function("ObjRender_GetZ", new Callback(Func_ObjRender_GetZ), 1),
            new Function("ObjRender_GetAngleX", new Callback(Func_ObjRender_GetAngleX), 1),
            new Function("ObjRender_GetAngleY", new Callback(Func_ObjRender_GetAngleY), 1),
            new Function("ObjRender_GetAngleZ", new Callback(Func_ObjRender_GetAngleZ), 1),
            new Function("ObjRender_GetScaleX", new Callback(Func_ObjRender_GetScaleX), 1),
            new Function("ObjRender_GetScaleY", new Callback(Func_ObjRender_GetScaleY), 1),
            new Function("ObjRender_GetScaleZ", new Callback(Func_ObjRender_GetScaleZ), 1),
            new Function("ObjRender_SetZWrite", new Callback(Func_ObjRender_SetZWrite), 2),
            new Function("ObjRender_SetZTest", new Callback(Func_ObjRender_SetZTest), 2),
            new Function("ObjRender_SetFogEnable", new Callback(Func_ObjRender_SetFogEnable), 2),
            new Function("ObjRender_SetCullingMode", new Callback(Func_ObjRender_SetCullingMode), 2),
            new Function("ObjRender_SetRalativeObject", new Callback(Func_ObjRender_SetRalativeObject), 3),
            new Function("ObjRender_SetPermitCamera", new Callback(Func_ObjRender_SetPermitCamera), 2),
            new Function("ObjRender_GetBlendType", new Callback(Func_ObjRender_GetBlendType), 1),

            //Dx�֐��F�I�u�W�F�N�g����(ShaderObject)
            new Function("ObjShader_Create", new Callback(Func_ObjShader_Create), 0),
            new Function("ObjShader_SetShaderF", new Callback(Func_ObjShader_SetShaderF), 2),
            new Function("ObjShader_SetShaderO", new Callback(Func_ObjShader_SetShaderO), 2),
            new Function("ObjShader_ResetShader", new Callback(Func_ObjShader_ResetShader), 1),
            new Function("ObjShader_SetTechnique", new Callback(Func_ObjShader_SetTechnique), 2),
            new Function("ObjShader_SetMatrix", new Callback(Func_ObjShader_SetMatrix), 3),
            new Function("ObjShader_SetMatrixArray", new Callback(Func_ObjShader_SetMatrixArray), 3),
            new Function("ObjShader_SetVector", new Callback(Func_ObjShader_SetVector), 6),
            new Function("ObjShader_SetFloat", new Callback(Func_ObjShader_SetFloat), 3),
            new Function("ObjShader_SetFloatArray", new Callback(Func_ObjShader_SetFloatArray), 3),
            new Function("ObjShader_SetTexture", new Callback(Func_ObjShader_SetTexture), 3),

            //Dx�֐��F�I�u�W�F�N�g����(PrimitiveObject)
            new Function("ObjPrim_Create", new Callback(Func_ObjPrimitive_Create), 1),
            new Function("ObjPrim_SetPrimitiveType", new Callback(Func_ObjPrimitive_SetPrimitiveType), 2),
            new Function("ObjPrim_SetVertexCount", new Callback(Func_ObjPrimitive_SetVertexCount), 2),
            new Function("ObjPrim_SetTexture", new Callback(Func_ObjPrimitive_SetTexture), 2),
            new Function("ObjPrim_GetVertexCount", new Callback(Func_ObjPrimitive_GetVertexCount), 1),
            new Function("ObjPrim_SetVertexPosition", new Callback(Func_ObjPrimitive_SetVertexPosition), 5),
            new Function("ObjPrim_SetVertexUV", new Callback(Func_ObjPrimitive_SetVertexUV), 4),
            new Function("ObjPrim_SetVertexUVT", new Callback(Func_ObjPrimitive_SetVertexUVT), 4),
            new Function("ObjPrim_SetVertexColor", new Callback(Func_ObjPrimitive_SetVertexColor), 5),
            new Function("ObjPrim_SetVertexAlpha", new Callback(Func_ObjPrimitive_SetVertexAlpha), 3),
            new Function("ObjPrim_GetVertexPosition", new Callback(Func_ObjPrimitive_GetVertexPosition), 2),

            //Dx�֐��F�I�u�W�F�N�g����(Sprite2D)
            new Function("ObjSprite2D_SetSourceRect", new Callback(Func_ObjSprite2D_SetSourceRect), 5),
            new Function("ObjSprite2D_SetDestRect", new Callback(Func_ObjSprite2D_SetDestRect), 5),
            new Function("ObjSprite2D_SetDestCenter", new Callback(Func_ObjSprite2D_SetDestCenter), 1),

            //Dx�֐��F�I�u�W�F�N�g����(SpriteList2D)
            new Function("ObjSpriteList2D_SetSourceRect", new Callback(Func_ObjSpriteList2D_SetSourceRect), 5),
            new Function("ObjSpriteList2D_SetDestRect", new Callback(Func_ObjSpriteList2D_SetDestRect), 5),
            new Function("ObjSpriteList2D_SetDestCenter", new Callback(Func_ObjSpriteList2D_SetDestCenter), 1),
            new Function("ObjSpriteList2D_AddVertex", new Callback(Func_ObjSpriteList2D_AddVertex), 1),
            new Function("ObjSpriteList2D_CloseVertex", new Callback(Func_ObjSpriteList2D_CloseVertex), 1),
            new Function("ObjSpriteList2D_ClearVertexCount", new Callback(Func_ObjSpriteList2D_ClearVertexCount), 1),

            //Dx�֐��F�I�u�W�F�N�g����(Sprite3D)
            new Function("ObjSprite3D_SetSourceRect", new Callback(Func_ObjSprite3D_SetSourceRect), 5),
            new Function("ObjSprite3D_SetDestRect", new Callback(Func_ObjSprite3D_SetDestRect), 5),
            new Function("ObjSprite3D_SetSourceDestRect", new Callback(Func_ObjSprite3D_SetSourceDestRect), 5),
            new Function("ObjSprite3D_SetBillboard", new Callback(Func_ObjSprite3D_SetBillboard), 2),

            //Dx�֐��F�I�u�W�F�N�g����(TrajectoryObject3D)
            new Function("ObjTrajectory3D_SetInitialPoint", new Callback(Func_ObjTrajectory3D_SetInitialPoint), 7),
            new Function("ObjTrajectory3D_SetAlphaVariation", new Callback(Func_ObjTrajectory3D_SetAlphaVariation), 2),
            new Function("ObjTrajectory3D_SetComplementCount", new Callback(Func_ObjTrajectory3D_SetComplementCount), 2),

            //Dx�֐��F�I�u�W�F�N�g����(DxMesh)
            new Function("ObjMesh_Create", new Callback(Func_ObjMesh_Create), 0),
            new Function("ObjMesh_Load", new Callback(Func_ObjMesh_Load), 2),
            new Function("ObjMesh_SetColor", new Callback(Func_ObjMesh_SetColor), 4),
            new Function("ObjMesh_SetAlpha", new Callback(Func_ObjMesh_SetAlpha), 2),
            new Function("ObjMesh_SetAnimation", new Callback(Func_ObjMesh_SetAnimation), 3),
            new Function("ObjMesh_SetCoordinate2D", new Callback(Func_ObjMesh_SetCoordinate2D), 2),
            new Function("ObjMesh_GetPath", new Callback(Func_ObjMesh_GetPath), 1),

            //Dx�֐��F�e�L�X�g����(DxText)
            new Function("ObjText_Create", new Callback(Func_ObjText_Create), 0),
            new Function("ObjText_SetText", new Callback(Func_ObjText_SetText), 2),
            new Function("ObjText_SetFontType", new Callback(Func_ObjText_SetFontType), 2),
            new Function("ObjText_SetFontSize", new Callback(Func_ObjText_SetFontSize), 2),
            new Function("ObjText_SetFontBold", new Callback(Func_ObjText_SetFontBold), 2),
            new Function("ObjText_SetFontColorTop", new Callback(Func_ObjText_SetFontColorTop), 4),
            new Function("ObjText_SetFontColorBottom", new Callback(Func_ObjText_SetFontColorBottom), 4),
            new Function("ObjText_SetFontBorderWidth", new Callback(Func_ObjText_SetFontBorderWidth), 2),
            new Function("ObjText_SetFontBorderType", new Callback(Func_ObjText_SetFontBorderType), 2),
            new Function("ObjText_SetFontBorderColor", new Callback(Func_ObjText_SetFontBorderColor), 4),
            new Function("ObjText_SetMaxWidth", new Callback(Func_ObjText_SetMaxWidth), 2),
            new Function("ObjText_SetMaxHeight", new Callback(Func_ObjText_SetMaxHeight), 2),
            new Function("ObjText_SetLinePitch", new Callback(Func_ObjText_SetLinePitch), 2),
            new Function("ObjText_SetSidePitch", new Callback(Func_ObjText_SetSidePitch), 2),
            new Function("ObjText_SetVertexColor", new Callback(Func_ObjText_SetVertexColor), 5),
            new Function("ObjText_SetTransCenter", new Callback(Func_ObjText_SetTransCenter), 3),
            new Function("ObjText_SetAutoTransCenter", new Callback(Func_ObjText_SetAutoTransCenter), 2),
            new Function("ObjText_SetHorizontalAlignment", new Callback(Func_ObjText_SetHorizontalAlignment), 2),
            new Function("ObjText_SetSyntacticAnalysis", new Callback(Func_ObjText_SetSyntacticAnalysis), 2),
            new Function("ObjText_GetTextLength", new Callback(Func_ObjText_GetTextLength), 1),
            new Function("ObjText_GetTextLengthCU", new Callback(Func_ObjText_GetTextLengthCU), 1),
            new Function("ObjText_GetTextLengthCUL", new Callback(Func_ObjText_GetTextLengthCUL), 1),
            new Function("ObjText_GetTotalWidth", new Callback(Func_ObjText_GetTotalWidth), 1),
            new Function("ObjText_GetTotalHeight", new Callback(Func_ObjText_GetTotalHeight), 1),

            //Dx�֐��F��������(DxSoundObject)
            new Function("ObjSound_Create", new Callback(Func_ObjSound_Create), 0),
            new Function("ObjSound_Load", new Callback(Func_ObjSound_Load), 2),
            new Function("ObjSound_Play", new Callback(Func_ObjSound_Play), 1),
            new Function("ObjSound_Stop", new Callback(Func_ObjSound_Stop), 1),
            new Function("ObjSound_SetVolumeRate", new Callback(Func_ObjSound_SetVolumeRate), 2),
            new Function("ObjSound_SetPanRate", new Callback(Func_ObjSound_SetPanRate), 2),
            new Function("ObjSound_SetFade", new Callback(Func_ObjSound_SetFade), 2),
            new Function("ObjSound_SetLoopEnable", new Callback(Func_ObjSound_SetLoopEnable), 2),
            new Function("ObjSound_SetLoopTime", new Callback(Func_ObjSound_SetLoopTime), 3),
            new Function("ObjSound_SetLoopSampleCount", new Callback(Func_ObjSound_SetLoopSampleCount), 3),
            new Function("ObjSound_SetRestartEnable", new Callback(Func_ObjSound_SetRestartEnable), 2),
            new Function("ObjSound_SetSoundDivision", new Callback(Func_ObjSound_SetSoundDivision), 2),
            new Function("ObjSound_IsPlaying", new Callback(Func_ObjSound_IsPlaying), 1),
            new Function("ObjSound_GetVolumeRate", new Callback(Func_ObjSound_GetVolumeRate), 1),

            //Dx�֐��F�t�@�C������(DxFileObject)
            new Function("ObjFile_Create", new Callback(Func_ObjFile_Create), 1),
            new Function("ObjFile_Open", new Callback(Func_ObjFile_Open), 2),
            new Function("ObjFile_OpenNW", new Callback(Func_ObjFile_OpenNW), 2),
            new Function("ObjFile_Store", new Callback(Func_ObjFile_Store), 1),
            new Function("ObjFile_GetSize", new Callback(Func_ObjFile_GetSize), 1),

            //Dx�֐��F�t�@�C������(DxTextFileObject)
            new Function("ObjFileT_GetLineCount", new Callback(Func_ObjFileT_GetLineCount), 1),
            new Function("ObjFileT_GetLineText", new Callback(Func_ObjFileT_GetLineText), 2),
            new Function("ObjFileT_SplitLineText", new Callback(Func_ObjFileT_SplitLineText), 3),
            new Function("ObjFileT_AddLine", new Callback(Func_ObjFileT_AddLine), 2),
            new Function("ObjFileT_ClearLine", new Callback(Func_ObjFileT_ClearLine), 1),

            ////Dx�֐��F�t�@�C������(DxBinalyFileObject)
            new Function("ObjFileB_SetByteOrder", new Callback(Func_ObjFileB_SetByteOrder), 2),
            new Function("ObjFileB_SetCharacterCode", new Callback(Func_ObjFileB_SetCharacterCode), 2),
            new Function("ObjFileB_GetPointer", new Callback(Func_ObjFileB_GetPointer), 1),
            new Function("ObjFileB_Seek", new Callback(Func_ObjFileB_Seek), 2),
            new Function("ObjFileB_ReadBoolean", new Callback(Func_ObjFileB_ReadBoolean), 1),
            new Function("ObjFileB_ReadByte", new Callback(Func_ObjFileB_ReadByte), 1),
            new Function("ObjFileB_ReadShort", new Callback(Func_ObjFileB_ReadShort), 1),
            new Function("ObjFileB_ReadInteger", new Callback(Func_ObjFileB_ReadInteger), 1),
            new Function("ObjFileB_ReadLong", new Callback(Func_ObjFileB_ReadLong), 1),
            new Function("ObjFileB_ReadFloat", new Callback(Func_ObjFileB_ReadFloat), 1),
            new Function("ObjFileB_ReadDouble", new Callback(Func_ObjFileB_ReadDouble), 1),
            new Function("ObjFileB_ReadString", new Callback(Func_ObjFileB_ReadString), 2),

            //�萔
            new Function("ID_INVALID",constant<new Callback(ID_INVALID>::func,0),
            new Function("OBJ_PRIMITIVE_2D",constant<new Callback(OBJ_PRIMITIVE_2D>::func,0),
            new Function("OBJ_SPRITE_2D",constant<new Callback(OBJ_SPRITE_2D>::func,0),
            new Function("OBJ_SPRITE_LIST_2D",constant<new Callback(OBJ_SPRITE_LIST_2D>::func,0),
            new Function("OBJ_PRIMITIVE_3D",constant<new Callback(OBJ_PRIMITIVE_3D>::func,0),
            new Function("OBJ_SPRITE_3D",constant<new Callback(OBJ_SPRITE_3D>::func,0),
            new Function("OBJ_TRAJECTORY_3D",constant<new Callback(OBJ_TRAJECTORY_3D>::func,0),
            new Function("OBJ_SHADER",constant<new Callback(OBJ_SHADER>::func,0),
            new Function("OBJ_MESH",constant<new Callback(OBJ_MESH>::func,0),
            new Function("OBJ_TEXT",constant<new Callback(OBJ_TEXT>::func,0),
            new Function("OBJ_SOUND",constant<new Callback(OBJ_SOUND>::func,0),
            new Function("OBJ_FILE_TEXT",constant<new Callback(OBJ_FILE_TEXT>::func,0),
            new Function("OBJ_FILE_BINARY",constant<new Callback(OBJ_FILE_BINARY>::func,0),

            new Function("BLEND_NONE",constant<DirectGraphics::MODE_BLEND_NONE>::func,0),
            new Function("BLEND_ALPHA",constant<DirectGraphics::MODE_BLEND_ALPHA>::func,0),
            new Function("BLEND_ADD_RGB",constant<DirectGraphics::MODE_BLEND_ADD_RGB>::func,0),
            new Function("BLEND_ADD_ARGB",constant<DirectGraphics::MODE_BLEND_ADD_ARGB>::func,0),
            new Function("BLEND_MULTIPLY",constant<DirectGraphics::MODE_BLEND_MULTIPLY>::func,0),
            new Function("BLEND_SUBTRACT",constant<DirectGraphics::MODE_BLEND_SUBTRACT>::func,0),
            new Function("BLEND_SHADOW",constant<DirectGraphics::MODE_BLEND_SHADOW>::func,0),
            new Function("BLEND_INV_DESTRGB",constant<DirectGraphics::MODE_BLEND_INV_DESTRGB>::func,0),
            new Function("CULL_NONE",constant<D3DCULL_NONE>::func,0),
            new Function("CULL_CW",constant<D3DCULL_CW>::func,0),
            new Function("CULL_CCW",constant<D3DCULL_CCW>::func,0),

            new Function("PRIMITIVE_POINT_LIST",constant<D3DPT_POINTLIST>::func,0),
            new Function("PRIMITIVE_LINELIST",constant<D3DPT_LINELIST>::func,0),
            new Function("PRIMITIVE_LINESTRIP",constant<D3DPT_LINESTRIP>::func,0),
            new Function("PRIMITIVE_TRIANGLELIST",constant<D3DPT_TRIANGLELIST>::func,0),
            new Function("PRIMITIVE_TRIANGLESTRIP",constant<D3DPT_TRIANGLESTRIP>::func,0),
            new Function("PRIMITIVE_TRIANGLEFAN",constant<D3DPT_TRIANGLEFAN>::func,0),

            new Function("BORDER_NONE",constant<DxFont::BORDER_NONE>::func,0),
            new Function("BORDER_FULL",constant<DxFont::BORDER_FULL>::func,0),
            new Function("BORDER_SHADOW",constant<DxFont::BORDER_SHADOW>::func,0),

            new Function("SOUND_BGM",constant<SoundDivision::DIVISION_BGM>::func,0),
            new Function("SOUND_SE",constant<SoundDivision::DIVISION_SE>::func,0),
            new Function("SOUND_VOICE",constant<SoundDivision::DIVISION_VOICE>::func,0),

            new Function("ALIGNMENT_LEFT",constant<DxText::ALIGNMENT_LEFT>::func,0),
            new Function("ALIGNMENT_RIGHT",constant<DxText::ALIGNMENT_RIGHT>::func,0),
            new Function("ALIGNMENT_CENTER",constant<DxText::ALIGNMENT_CENTER>::func,0),

            new Function("CODE_ACP",constant<new Callback(CODE_ACP>::func,0),
            new Function("CODE_UTF8",constant<new Callback(CODE_UTF8>::func,0),
            new Function("CODE_UTF16LE",constant<new Callback(CODE_UTF16LE>::func,0),
            new Function("CODE_UTF16BE",constant<new Callback(CODE_UTF16BE>::func,0),

            new Function("ENDIAN_LITTLE",constant<ByteOrder::ENDIAN_LITTLE>::func,0),
            new Function("ENDIAN_BIG",constant<ByteOrder::ENDIAN_BIG>::func,0),

            //DirectInput
            new Function("KEY_FREE",constant<KEY_FREE>::func,0),
            new Function("KEY_PUSH",constant<KEY_PUSH>::func,0),
            new Function("KEY_PULL",constant<KEY_PULL>::func,0),
            new Function("KEY_HOLD",constant<KEY_HOLD>::func,0),

            new Function("MOUSE_LEFT",constant<DI_MOUSE_LEFT>::func,0),
            new Function("MOUSE_RIGHT",constant<DI_MOUSE_RIGHT>::func,0),
            new Function("MOUSE_MIDDLE",constant<DI_MOUSE_MIDDLE>::func,0),

            new Function("KEY_ESCAPE",constant<DIK_ESCAPE>::func,0),
            new Function("KEY_1",constant<DIK_1>::func,0),
            new Function("KEY_2",constant<DIK_2>::func,0),
            new Function("KEY_3",constant<DIK_3>::func,0),
            new Function("KEY_4",constant<DIK_4>::func,0),
            new Function("KEY_5",constant<DIK_5>::func,0),
            new Function("KEY_6",constant<DIK_6>::func,0),
            new Function("KEY_7",constant<DIK_7>::func,0),
            new Function("KEY_8",constant<DIK_8>::func,0),
            new Function("KEY_9",constant<DIK_9>::func,0),
            new Function("KEY_0",constant<DIK_0>::func,0),
            new Function("KEY_MINUS",constant<DIK_MINUS>::func,0),
            new Function("KEY_EQUALS",constant<DIK_EQUALS>::func,0),
            new Function("KEY_BACK",constant<DIK_BACK>::func,0),
            new Function("KEY_TAB",constant<DIK_TAB>::func,0),
            new Function("KEY_Q",constant<DIK_Q>::func,0),
            new Function("KEY_W",constant<DIK_W>::func,0),
            new Function("KEY_E",constant<DIK_E>::func,0),
            new Function("KEY_R",constant<DIK_R>::func,0),
            new Function("KEY_T",constant<DIK_T>::func,0),
            new Function("KEY_Y",constant<DIK_Y>::func,0),
            new Function("KEY_U",constant<DIK_U>::func,0),
            new Function("KEY_I",constant<DIK_I>::func,0),
            new Function("KEY_O",constant<DIK_O>::func,0),
            new Function("KEY_P",constant<DIK_P>::func,0),
            new Function("KEY_LBRACKET",constant<DIK_LBRACKET>::func,0),
            new Function("KEY_RBRACKET",constant<DIK_RBRACKET>::func,0),
            new Function("KEY_RETURN",constant<DIK_RETURN>::func,0),
            new Function("KEY_LCONTROL",constant<DIK_LCONTROL>::func,0),
            new Function("KEY_A",constant<DIK_A>::func,0),
            new Function("KEY_S",constant<DIK_S>::func,0),
            new Function("KEY_D",constant<DIK_D>::func,0),
            new Function("KEY_F",constant<DIK_F>::func,0),
            new Function("KEY_G",constant<DIK_G>::func,0),
            new Function("KEY_H",constant<DIK_H>::func,0),
            new Function("KEY_J",constant<DIK_J>::func,0),
            new Function("KEY_K",constant<DIK_K>::func,0),
            new Function("KEY_L",constant<DIK_L>::func,0),
            new Function("KEY_SEMICOLON",constant<DIK_SEMICOLON>::func,0),
            new Function("KEY_APOSTROPHE",constant<DIK_APOSTROPHE>::func,0),
            new Function("KEY_GRAVE",constant<DIK_GRAVE>::func,0),
            new Function("KEY_LSHIFT",constant<DIK_LSHIFT>::func,0),
            new Function("KEY_BACKSLASH",constant<DIK_BACKSLASH>::func,0),
            new Function("KEY_Z",constant<DIK_Z>::func,0),
            new Function("KEY_X",constant<DIK_X>::func,0),
            new Function("KEY_C",constant<DIK_C>::func,0),
            new Function("KEY_V",constant<DIK_V>::func,0),
            new Function("KEY_B",constant<DIK_B>::func,0),
            new Function("KEY_N",constant<DIK_N>::func,0),
            new Function("KEY_M",constant<DIK_M>::func,0),
            new Function("KEY_COMMA",constant<DIK_COMMA>::func,0),
            new Function("KEY_PERIOD",constant<DIK_PERIOD>::func,0),
            new Function("KEY_SLASH",constant<DIK_SLASH>::func,0),
            new Function("KEY_RSHIFT",constant<DIK_RSHIFT>::func,0),
            new Function("KEY_MULTIPLY",constant<DIK_MULTIPLY>::func,0),
            new Function("KEY_LMENU",constant<DIK_LMENU>::func,0),
            new Function("KEY_SPACE",constant<DIK_SPACE>::func,0),
            new Function("KEY_CAPITAL",constant<DIK_CAPITAL>::func,0),
            new Function("KEY_F1",constant<DIK_F1>::func,0),
            new Function("KEY_F2",constant<DIK_F2>::func,0),
            new Function("KEY_F3",constant<DIK_F3>::func,0),
            new Function("KEY_F4",constant<DIK_F4>::func,0),
            new Function("KEY_F5",constant<DIK_F5>::func,0),
            new Function("KEY_F6",constant<DIK_F6>::func,0),
            new Function("KEY_F7",constant<DIK_F7>::func,0),
            new Function("KEY_F8",constant<DIK_F8>::func,0),
            new Function("KEY_F9",constant<DIK_F9>::func,0),
            new Function("KEY_F10",constant<DIK_F10>::func,0),
            new Function("KEY_NUMLOCK",constant<DIK_NUMLOCK>::func,0),
            new Function("KEY_SCROLL",constant<DIK_SCROLL>::func,0),
            new Function("KEY_NUMPAD7",constant<DIK_NUMPAD7>::func,0),
            new Function("KEY_NUMPAD8",constant<DIK_NUMPAD8>::func,0),
            new Function("KEY_NUMPAD9",constant<DIK_NUMPAD9>::func,0),
            new Function("KEY_SUBTRACT",constant<DIK_SUBTRACT>::func,0),
            new Function("KEY_NUMPAD4",constant<DIK_NUMPAD4>::func,0),
            new Function("KEY_NUMPAD5",constant<DIK_NUMPAD5>::func,0),
            new Function("KEY_NUMPAD6",constant<DIK_NUMPAD6>::func,0),
            new Function("KEY_ADD",constant<DIK_ADD>::func,0),
            new Function("KEY_NUMPAD1",constant<DIK_NUMPAD1>::func,0),
            new Function("KEY_NUMPAD2",constant<DIK_NUMPAD2>::func,0),
            new Function("KEY_NUMPAD3",constant<DIK_NUMPAD3>::func,0),
            new Function("KEY_NUMPAD0",constant<DIK_NUMPAD0>::func,0),
            new Function("KEY_DECIMAL",constant<DIK_DECIMAL>::func,0),
            new Function("KEY_F11",constant<DIK_F11>::func,0),
            new Function("KEY_F12",constant<DIK_F12>::func,0),
            new Function("KEY_F13",constant<DIK_F13>::func,0),
            new Function("KEY_F14",constant<DIK_F14>::func,0),
            new Function("KEY_F15",constant<DIK_F15>::func,0),
            new Function("KEY_KANA",constant<DIK_KANA>::func,0),
            new Function("KEY_CONVERT",constant<DIK_CONVERT>::func,0),
            new Function("KEY_NOCONVERT",constant<DIK_NOCONVERT>::func,0),
            new Function("KEY_YEN",constant<DIK_YEN>::func,0),
            new Function("KEY_NUMPADEQUALS",constant<DIK_NUMPADEQUALS>::func,0),
            new Function("KEY_CIRCUMFLEX",constant<DIK_CIRCUMFLEX>::func,0),
            new Function("KEY_AT",constant<DIK_AT>::func,0),
            new Function("KEY_COLON",constant<DIK_COLON>::func,0),
            new Function("KEY_UNDERLINE",constant<DIK_UNDERLINE>::func,0),
            new Function("KEY_KANJI",constant<DIK_KANJI>::func,0),
            new Function("KEY_STOP",constant<DIK_STOP>::func,0),
            new Function("KEY_AX",constant<DIK_AX>::func,0),
            new Function("KEY_UNLABELED",constant<DIK_UNLABELED>::func,0),
            new Function("KEY_NUMPADENTER",constant<DIK_NUMPADENTER>::func,0),
            new Function("KEY_RCONTROL",constant<DIK_RCONTROL>::func,0),
            new Function("KEY_NUMPADCOMMA",constant<DIK_NUMPADCOMMA>::func,0),
            new Function("KEY_DIVIDE",constant<DIK_DIVIDE>::func,0),
            new Function("KEY_SYSRQ",constant<DIK_SYSRQ>::func,0),
            new Function("KEY_RMENU",constant<DIK_RMENU>::func,0),
            new Function("KEY_PAUSE",constant<DIK_PAUSE>::func,0),
            new Function("KEY_HOME",constant<DIK_HOME>::func,0),
            new Function("KEY_UP",constant<DIK_UP>::func,0),
            new Function("KEY_PRIOR",constant<DIK_PRIOR>::func,0),
            new Function("KEY_LEFT",constant<DIK_LEFT>::func,0),
            new Function("KEY_RIGHT",constant<DIK_RIGHT>::func,0),
            new Function("KEY_END",constant<DIK_END>::func,0),
            new Function("KEY_DOWN",constant<DIK_DOWN>::func,0),
            new Function("KEY_NEXT",constant<DIK_NEXT>::func,0),
            new Function("KEY_INSERT",constant<DIK_INSERT>::func,0),
            new Function("KEY_DELETE",constant<DIK_DELETE>::func,0),
            new Function("KEY_LWIN",constant<DIK_LWIN>::func,0),
            new Function("KEY_RWIN",constant<DIK_RWIN>::func,0),
            new Function("KEY_APPS",constant<DIK_APPS>::func,0),
            new Function("KEY_POWER",constant<DIK_POWER>::func,0),
            new Function("KEY_SLEEP",constant<DIK_SLEEP>::func,0),
        */};
    }
}
